version: "3"
services:
  redis:
    image: redis

  mongodb:
    image: mongo
    volumes:
      - /tmp/mongo:/data/db

  mosca:
    image: matteocollina/mosca
    volumes:
      - /tmp/mosca:/db

  publisher:
    build: publisher
    image: publisher_small
    container_name: my-publisher_small
    depends_on:
      - "mosca"
      - "subscriber"

  subscriber:
    build: subscriber
    image: subscriber_small
    container_name: my-subscriber_small
    depends_on:
      - "redis"
      - "mongodb"
      - "mosca"
