# Simple docker complse override configuration file for chapter4/ application

version: "3"
services:
  redis:
    image: redis
    container_name: my-redis
    volumes:
      - /tmp/redis:/data
    ports:
      - 6379:6379

  mongodb:
    image: mongo
    container_name: my-mongo
    volumes:
      - /tmp/mongo:/data/db
    ports:
      - 27017:27017

  mosca:
    image: matteocollina/mosca
    container_name: my-mosca
    volumes:
      - /tmp/mosca:/db
    ports:
      - 1883:1883
      - 80:80

  publisher:
    build: publisher
    image: publisher
    container_name: my-publisher
    environment:
      - MQTT_HOST=${HOSTIP}
      - REDIS_HOST=${HOSTIP}
      - MONGO_HOST=${HOSTIP}
    ports:
      - 3000:3000

  subscriber:
    build: subscriber
    image: subscriber
    container_name: my-subscriber
    environment:
      - MQTT_HOST=${HOSTIP}
      - REDIS_HOST=${HOSTIP}
      - MONGO_HOST=${HOSTIP}
